#この仕様は以下の事を行います。
# - ECRへのログイン
# - docker build
# - docker tag
# - docker push
# - imagedefinitions.jsonの作成 (https://docs.aws.amazon.com/codepipeline/latest/userguide/file-reference.html)
#環境変数
# - AWS_DEFAULT_REGION : リージョン ID の値
# - IMAGE_TAG : ビルドに使用するタグの参考 (https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-env-ref-env-vars.html)
# - IMAGE_REPO_URI : Amazon ECR respository URI の値
# - CONTAINER_NAME : コンテナ名

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_NUMBER)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t myapp:$IMAGE_TAG .
      - docker tag myapp:$IMAGE_TAG $IMAGE_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"%s\"}]" $IMAGE_REPO_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json
      - cat $CODEBUILD_SRC_DIR/imagedefinitions.json
artifacts:
    files: imagedefinitions.json